### ISSUE TITLE
Health checking is KO

### ISSUE THREAD

**Issue by comassky** [qdm12/cloudflare-dns-server#23]
Hi all,

Very awesome work ! Thanks ;)

I noticed that the container could not go to healthy => remains on starting
`
72bd9443b31f        qmcgaw/cloudflare-dns-server   "/bin/sh -c /unbound…"   4 minutes ago       Up 4 minutes (health: starting)                                                        Dns`

Ping of duckduckgo inside container is KO

![image](https://user-images.githubusercontent.com/48486646/72370782-3a412980-3703-11ea-8792-8f73aea00b9e.png)

The dns works very well

```
$ dig @localhost duckduckgo.com

; <<>> DiG 9.11.5-P4-5.1-Debian <<>> @localhost duckduckgo.com
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 3738
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;duckduckgo.com.                        IN      A

;; ANSWER SECTION:
duckduckgo.com.         3532    IN      A       46.51.179.90
duckduckgo.com.         3532    IN      A       79.125.105.113
duckduckgo.com.         3532    IN      A       176.34.155.23

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: mar. janv. 14 19:23:02 CET 2020
;; MSG SIZE  rcvd: 91
```

This is my docker-compose

```yml
cloudflare-dns-server:
   environment:
     - VERBOSITY=1
     - VERBOSITY_DETAILS=0
     - PROVIDERS=cloudflare,quad9
     - BLOCK_NSA=on
  image: qmcgaw/cloudflare-dns-server
  container_name: Dns
  network_mode: host
```

**Comment by qdm12** [comment]
Hi there,

Thanks for your message and the compliment :smiley:

- Do you mean that the healthcheck keeps on being on `Starting`? If so, it is meant to run every 5 minutes that's why, line [here](https://github.com/qdm12/cloudflare-dns-server/blob/master/Dockerfile#L43)
- Pinging requires you to run as root in the container but the container runs without root (more secured) that's why pinging does not work
- You should ideally run the container with `network_mode: bridge` and a port mapping `- 53:53/udp` for added security

Enjoy!

**Comment by comassky** [comment]
Thanks !

Still "Starting" (49 minutes)

`72bd9443b31f        qmcgaw/cloudflare-dns-server   "/bin/sh -c /unbound…"   3 hours ago         Up 49 minutes (unhealthy)                                                        Dns`

I set bridge networks now ! Thanks.

But still "Starting" :)

**Comment by qdm12** [comment]
There is indeed an error with `dig` (`Error relocating /lib/libcom_err.so.2: secure_getenv: symbol not found`) hence the healthcheck failing, I will investigate in the coming days. Thanks for reporting this. I'll close the issue once it's fixed.

**Comment by comassky** [comment]
It seems that glibc is not installed on the alpines, causing this bug

https://stackoverflow.com/questions/37818831/is-there-a-best-practice-on-setting-up-glibc-on-docker-alpine-linux-base-image

https://wiki.alpinelinux.org/wiki/Running_glibc_programs

**Comment by qdm12** [comment]
Yes I know, although dig worked before as it's added from the alpine packages. I'm planning on replacing the shell scripting with a Go written program quite soon, so it'll probably get fixed with this as the healthcheck won't rely on dig anymore.

**Comment by qdm12** [comment]
I just rebuilt the image without changing anything and it seems `bind-tools` and *dig* got fixed by the Alpine team. The container is now healthy after 5 minutes, please simply pull the newer image and restart the container

```sh
docker pull qmcgaw/cloudflare-dns-server
```

Enjoy 🎉

**Comment by comassky** [comment]
qmcgaw/cloudflare-dns-server   latest              14dbf142d1a1        31 minutes ago      49MB

Still not working for me


```
14:18:50 › docker exec -it Dns sh
/unbound $ dig google.fr
Error relocating /lib/libcom_err.so.2: secure_getenv: symbol not found
/unbound $

```

`8081f2099d8d        qmcgaw/cloudflare-dns-server:latest   "/bin/sh -c /unbound…"   5 minutes ago       Up 5 minutes (unhealthy)   0.0.0.0:53->53/udp                                   Dns
`

**Comment by qdm12** [comment]
Indeed, I just pulled the image and it doesn't work.

Can you try building it (you need git):

```sh
docker build -t qmcgaw/cloudflare-dns-server https://github.com/qdm12/cloudflare-dns-server.git
```

It might be a problem on the CI pipeline, that's quite strange.

**Comment by comassky** [comment]
`15:12:59 › docker build -t qmcgaw/cloudflare-dns-server https://github.com/qdm12/cloudflare-dns-server.git
Sending build context to Docker daemon  22.02kB
Step 1/24 : ARG ALPINE_VERSION=3.10
Step 2/24 : FROM alpine:${ALPINE_VERSION} AS updated
3.10: Pulling from library/alpine
89d9c30c1d48: Already exists
Digest: sha256:c19173c5ada610a5989151111163d28a67368362762534d8a8121ce95cf2bd5a
Status: Downloaded newer image for alpine:3.10
 ---> 965ea09ff2eb
Step 3/24 : WORKDIR /tmp/updated
 ---> Running in 4faa809eda10
Removing intermediate container 4faa809eda10
 ---> 270b176723c2
Step 4/24 : RUN wget -q https://raw.githubusercontent.com/qdm12/files/master/named.root.updated -O root.hints &&     wget -q https://raw.githubusercontent.com/qdm12/files/master/root.key.updated -O root.key
 ---> Running in 65bd50c2ba60
wget: bad address 'raw.githubusercontent.com'
The command '/bin/sh -c wget -q https://raw.githubusercontent.com/qdm12/files/master/named.root.updated -O root.hints &&     wget -q https://raw.githubusercontent.com/qdm12/files/master/root.key.updated -O root.key' returned a non-zero code: 1
[1]    2646 exit 1     docker build -t qmcgaw/cloudflare-dns-server
`

:/

**Comment by qdm12** [comment]
That's probably a problem on your network. I built it with the same command and the Github rawusercontent URLs are fine. By the way, it works if it's built on my machine, so it's definitely related to a CI build problem.

**Comment by juhovan** [comment]
Hello,

I'm also seeing this and building from source didn't fix it for me.
However building on Alpine 3.11 instead of 3.10 fixes dig (and healthcheck) and haven't noticed any issues yet in my very limited testing.

**Comment by qdm12** [comment]
I just pushed a commit to upgrade to Alpine 3.11. It works with `dig` when I build it on a Linux host (Arch, Alpine) and Windows, let's see if it works out with the image built from Travis. It might take quite some time (~30 minutes) to finish building all the images on Travis.

**Comment by qdm12** [comment]
I just pulled the image built by Travis CI

```sh
docker pull qmcgaw/cloudflare-dns-server
```

And running `docker exec -it <dns-container-name> dig` now works.

No idea why it did not work before, but the Alpine upgrade seems to have fixed it. Feel free to reopen the issue.
