### ISSUE TITLE
LibreDNS still not working

### ISSUE THREAD

**Issue by axel-dd** [qdm12/cloudflare-dns-server#48]
Hi Quentin,
LibreDNS still does not work after the IP change fix. Can it be that LibreDNS does not support unencrypted DNS? Is there a quick solution for this?

logs:

```
=========================================
========= DNS over TLS container ========
=========================================
=========================================
=== Made with ❤️  by github.com/qdm12 ====
=========================================

Running version latest built on 2020-12-29T15:48:02Z (commit 347fe26)

🔧  Need help? https://github.com/qdm12/cloudflare-dns-server/issues/new
💻  Email? quentin.mcgaw@gmail.com
☕  Slack? Join from the Slack button on Github
💸  Help me? https://github.com/sponsors/qdm12
2020-12-29T16:48:35.970Z	INFO	Unbound version: 1.10.1
2020-12-29T16:48:35.970Z	INFO	Settings summary:
DNS over TLS provider:
|--libredns
Listening port: 53
Caching: enabled
IPv4 resolution: enabled
IPv6 resolution: disabled
Verbosity level: 1/5
Verbosity details level: 0/4
Validation log level: 0/2
Block malicious: enabled
Block surveillance: disabled
Block ads: disabled
Blocked hostnames:
Blocked IP addresses:
Allowed hostnames:
Private addresses: 
 |--127.0.0.1/8
 |--10.0.0.0/8
 |--172.16.0.0/12
 |--192.168.0.0/16
 |--169.254.0.0/16
 |--::1/128

 |--fc00::/7
 |--fe80::/10
 |--::ffff:0:0/96
Check Unbound: enabled
Update: every 24h0m0s
2020-12-29T16:48:35.970Z	INFO	using DNS address 116.202.176.26 internally
2020-12-29T16:48:35.971Z	INFO	healthcheck server: listening on 127.0.0.1:9999
2020-12-29T16:48:35.971Z	INFO	downloading root hints from https://raw.githubusercontent.com/qdm12/files/master/named.root.updated
2020-12-29T16:48:45.973Z	WARN	Get "https://raw.githubusercontent.com/qdm12/files/master/named.root.updated": dial tcp: lookup raw.githubusercontent.com on 127.0.0.11:53: read udp 192.168.2.6:50569->116.202.176.26:53: i/o timeout
2020-12-29T16:48:45.973Z	INFO	downloading root hints from https://raw.githubusercontent.com/qdm12/files/master/named.root.updated
2020-12-29T16:48:55.975Z	WARN	Get "https://raw.githubusercontent.com/qdm12/files/master/named.root.updated": dial tcp: lookup raw.githubusercontent.com on 127.0.0.11:53: read udp 192.168.2.6:52545->116.202.176.26:53: i/o timeout
2020-12-29T16:48:55.975Z	INFO	downloading root hints from https://raw.githubusercontent.com/qdm12/files/master/named.root.updated
2020-12-29T16:49:05.976Z	WARN	Get "https://raw.githubusercontent.com/qdm12/files/master/named.root.updated": dial tcp: lookup raw.githubusercontent.com on 127.0.0.11:53: read udp 192.168.2.6:37970->116.202.176.26:53: i/o timeout
```

**Comment by qdm12** [comment]
Fixed in 17cb054342175e7af8e05cbf425fc110155a7240

It was because the program was trying to use the DNS over plaintext to get the files at start. LibreDNS only supports DNS over TLS on port 853 and not plain DNS over 53 udp.

So now it just uses your default DNS you have setup in your network to resolve github.com. Subsequent file updates however will use DNS over TLS. I'll see what I can do to have these files bundled in the image so it doesn't leak the first DNS resolution at start.

**Comment by axel-dd** [comment]
Hi Quentin,
I tested libredns with the newest docker image. It still does not work.

logs:

```

=========================================

=========================================

=== Made with ❤️  by github.com/qdm12 ====

=========================================


Running version latest built on 2020-12-31T23:19:05Z (commit dd90001)



🔧  Need help? https://github.com/qdm12/cloudflare-dns-server/issues/new

💻  Email? quentin.mcgaw@gmail.com

☕  Slack? Join from the Slack button on Github

💸  Help me? https://github.com/sponsors/qdm12

2021-01-01T14:14:47.451Z	INFO	Unbound version: 1.10.1

2021-01-01T14:14:47.451Z	INFO	Settings summary:

DNS over TLS provider:

|--libredns

Listening port: 53

Caching: enabled

IPv4 resolution: enabled

IPv6 resolution: disabled

Verbosity level: 1/5

Verbosity details level: 0/4

Validation log level: 0/2

Block malicious: enabled

Block surveillance: disabled

Block ads: disabled

Blocked hostnames:

Blocked IP addresses:

Allowed hostnames:

Private addresses: 

 |--127.0.0.1/8

 |--10.0.0.0/8

 |--172.16.0.0/12

 |--192.168.0.0/16

 |--169.254.0.0/16

 |--::1/128

 |--fc00::/7

 |--fe80::/10

 |--::ffff:0:0/96

Check Unbound: enabled

Update: every 24h0m0s

2021-01-01T14:14:47.451Z	INFO	using DNS address 127.0.0.1 internally

2021-01-01T14:14:47.451Z	INFO	healthcheck server: listening on 127.0.0.1:9999

2021-01-01T14:14:47.451Z	INFO	generating Unbound configuration

2021-01-01T14:14:47.452Z	INFO	starting unbound

2021-01-01T14:14:47.482Z	INFO	unbound: [1609510487] unbound[12:0] notice: init module 0: validator

2021-01-01T14:14:47.482Z	INFO	unbound: [1609510487] unbound[12:0] notice: init module 1: iterator

2021-01-01T14:14:47.593Z	INFO	unbound: [1609510487] unbound[12:0] info: start of service (unbound 1.10.1).

2021-01-01T14:14:47.835Z	INFO	unbound: [1609510487] unbound[12:1] info: generate keytag query _ta-4a5c-4f66. NULL IN

2021-01-01T14:14:47.879Z	INFO	unbound: [1609510487] unbound[12:0] info: generate keytag query _ta-4a5c-4f66. NULL IN

2021-01-01T14:14:47.962Z	INFO	unbound: [1609510487] unbound[12:1] info: failed to prime trust anchor -- DNSKEY rrset is not secure . DNSKEY IN

2021-01-01T14:14:47.963Z	INFO	unbound: [1609510487] unbound[12:1] info: failed to prime trust anchor -- DNSKEY rrset is not secure . DNSKEY IN

2021-01-01T14:14:47.963Z	INFO	unbound: [1609510487] unbound[12:1] info: failed to prime trust anchor -- DNSKEY rrset is not secure . DNSKEY IN

2021-01-01T14:14:47.963Z	INFO	unbound: [1609510487] unbound[12:1] info: generate keytag query _ta-4a5c-4f66. NULL IN

2021-01-01T14:14:49.080Z	INFO	unbound: [1609510489] unbound[12:0] info: failed to prime trust anchor -- DNSKEY rrset is not secure . DNSKEY IN

2021-01-01T14:14:49.080Z	INFO	unbound: [1609510489] unbound[12:0] info: generate keytag query _ta-4a5c-4f66. NULL IN

2021-01-01T14:14:49.139Z	INFO	unbound: [1609510489] unbound[12:1] info: failed to prime trust anchor -- DNSKEY rrset is not secure . DNSKEY IN

2021-01-01T14:14:49.140Z	INFO	unbound: [1609510489] unbound[12:1] info: failed to prime trust anchor -- DNSKEY rrset is not secure . DNSKEY IN

2021-01-01T14:14:49.140Z	INFO	unbound: [1609510489] unbound[12:1] info: failed to prime trust anchor -- DNSKEY rrset is not secure . DNSKEY IN

2021-01-01T14:14:49.141Z	INFO	unbound: [1609510489] unbound[12:1] info: generate keytag query _ta-4a5c-4f66. NULL IN

2021-01-01T14:14:50.226Z	INFO	unbound: [1609510490] unbound[12:0] info: failed to prime trust anchor -- DNSKEY rrset is not secure . DNSKEY IN

2021-01-01T14:14:50.227Z	INFO	unbound: [1609510490] unbound[12:0] info: failed to prime trust anchor -- DNSKEY rrset is not secure . DNSKEY IN

2021-01-01T14:14:50.227Z	INFO	unbound: [1609510490] unbound[12:0] info: generate keytag query _ta-4a5c-4f66. NULL IN

2021-01-01T14:14:50.326Z	INFO	unbound: [1609510490] unbound[12:1] info: failed to prime trust anchor -- DNSKEY rrset is not secure . DNSKEY IN

2021-01-01T14:14:50.326Z	INFO	unbound: [1609510490] unbound[12:1] info: failed to prime trust anchor -- DNSKEY rrset is not secure . DNSKEY IN

2021-01-01T14:14:50.326Z	INFO	unbound: [1609510490] unbound[12:1] info: failed to prime trust anchor -- DNSKEY rrset is not secure . DNSKEY IN

2021-01-01T14:14:50.327Z	INFO	unbound: [1609510490] unbound[12:1] info: generate keytag query _ta-4a5c-4f66. NULL IN

2021-01-01T14:14:50.382Z	INFO	unbound: [1609510490] unbound[12:0] info: failed to prime trust anchor -- DNSKEY rrset is not secure . DNSKEY IN

2021-01-01T14:14:50.382Z	INFO	unbound: [1609510490] unbound[12:0] info: failed to prime trust anchor -- DNSKEY rrset is not secure . DNSKEY IN

2021-01-01T14:14:50.383Z	INFO	unbound: [1609510490] unbound[12:0] info: generate keytag query _ta-4a5c-4f66. NULL IN

2021-01-01T14:14:51.576Z	INFO	unbound: [1609510491] unbound[12:0] info: failed to prime trust anchor -- DNSKEY rrset is not secure . DNSKEY IN

2021-01-01T14:14:51.576Z	INFO	unbound: [1609510491] unbound[12:0] info: failed to prime trust anchor -- DNSKEY rrset is not secure . DNSKEY IN

2021-01-01T14:14:51.576Z	INFO	unbound: [1609510491] unbound[12:0] info: failed to prime trust anchor -- DNSKEY rrset is not secure . DNSKEY IN

2021-01-01T14:14:51.576Z	INFO	unbound: [1609510491] unbound[12:0] info: generate keytag query _ta-4a5c-4f66. NULL IN

2021-01-01T14:14:51.607Z	INFO	unbound: [1609510491] unbound[12:1] info: failed to prime trust anchor -- DNSKEY rrset is not secure . DNSKEY IN

2021-01-01T14:14:51.607Z	INFO	unbound: [1609510491] unbound[12:1] info: failed to prime trust anchor -- DNSKEY rrset is not secure . DNSKEY IN

2021-01-01T14:14:51.607Z	INFO	unbound: [1609510491] unbound[12:1] info: failed to prime trust anchor -- DNSKEY rrset is not secure . DNSKEY IN

2021-01-01T14:14:51.607Z	INFO	unbound: [1609510491] unbound[12:1] info: generate keytag query _ta-4a5c-4f66. NULL IN

2021-01-01T14:14:51.701Z	INFO	unbound: [1609510491] unbound[12:0] info: failed to prime trust anchor -- DNSKEY rrset is not secure . DNSKEY IN

2021-01-01T14:14:51.701Z	INFO	unbound: [1609510491] unbound[12:0] info: failed to prime trust anchor -- DNSKEY rrset is not secure . DNSKEY IN

2021-01-01T14:14:51.701Z	INFO	unbound: [1609510491] unbound[12:0] info: failed to prime trust anchor -- DNSKEY rrset is not secure . DNSKEY IN

2021-01-01T14:14:51.701Z	INFO	unbound: [1609510491] unbound[12:0] info: failed to prime trust anchor -- DNSKEY rrset is not secure . DNSKEY IN

2021-01-01T14:14:51.701Z	INFO	unbound: [1609510491] unbound[12:0] info: generate keytag query _ta-4a5c-4f66. NULL IN

2021-01-01T14:14:51.812Z	INFO	unbound: [1609510491] unbound[12:0] info: failed to prime trust anchor -- DNSKEY rrset is not secure . DNSKEY IN

2021-01-01T14:14:51.812Z	INFO	unbound: [1609510491] unbound[12:0] info: failed to prime trust anchor -- DNSKEY rrset is not secure . DNSKEY IN

2021-01-01T14:14:51.813Z	INFO	unbound: [1609510491] unbound[12:0] info: failed to prime trust anchor -- DNSKEY rrset is not secure . DNSKEY IN

2021-01-01T14:14:51.813Z	INFO	unbound: [1609510491] unbound[12:0] info: failed to prime trust anchor -- DNSKEY rrset is not secure . DNSKEY IN

2021-01-01T14:14:51.837Z	INFO	unbound: [1609510491] unbound[12:1] info: failed to prime trust anchor -- DNSKEY rrset is not secure . DNSKEY IN

2021-01-01T14:14:51.837Z	INFO	unbound: [1609510491] unbound[12:1] info: failed to prime trust anchor -- DNSKEY rrset is not secure . DNSKEY IN

2021-01-01T14:14:51.838Z	INFO	unbound: [1609510491] unbound[12:1] info: failed to prime trust anchor -- DNSKEY rrset is not secure . DNSKEY IN

2021-01-01T14:14:51.838Z	WARN	could not resolve github.com (try 1 of 10): lookup github.com on 127.0.0.11:53: server misbehaving

2021-01-01T14:14:52.339Z	WARN	could not resolve github.com (try 2 of 10): lookup github.com on 127.0.0.11:53: server misbehaving

2021-01-01T14:14:52.841Z	WARN	could not resolve github.com (try 3 of 10): lookup github.com on 127.0.0.11:53: server misbehaving

2021-01-01T14:14:53.343Z	WARN	could not resolve github.com (try 4 of 10): lookup github.com on 127.0.0.11:53: server misbehaving

2021-01-01T14:14:53.846Z	WARN	could not resolve github.com (try 5 of 10): lookup github.com on 127.0.0.11:53: server misbehaving

2021-01-01T14:14:54.347Z	WARN	could not resolve github.com (try 6 of 10): lookup github.com on 127.0.0.11:53: server misbehaving

2021-01-01T14:14:54.849Z	WARN	could not resolve github.com (try 7 of 10): lookup github.com on 127.0.0.11:53: server misbehaving

2021-01-01T14:14:55.351Z	WARN	could not resolve github.com (try 8 of 10): lookup github.com on 127.0.0.11:53: server misbehaving

2021-01-01T14:14:55.853Z	WARN	could not resolve github.com (try 9 of 10): lookup github.com on 127.0.0.11:53: server misbehaving

2021-01-01T14:14:56.355Z	WARN	could not resolve github.com (try 10 of 10): lookup github.com on 127.0.0.11:53: server misbehaving

```

With quad9 everywing works well. libredns is online but supports DoT only.

```
$ kdig @116.202.176.26 heise.de +tls
;; TLS session (TLS1.3)-(ECDHE-SECP256R1)-(RSA-PSS-RSAE-SHA256)-(AES-256-GCM)
;; ->>HEADER<<- opcode: QUERY; status: NOERROR; id: 49891
;; Flags: qr rd ra; QUERY: 1; ANSWER: 1; AUTHORITY: 0; ADDITIONAL: 1

;; EDNS PSEUDOSECTION:
;; Version: 0; flags: ; UDP size: 512 B; ext-rcode: NOERROR

;; QUESTION SECTION:
;; heise.de.                    IN      A

;; ANSWER SECTION:
heise.de.               86374   IN      A       193.99.144.80

;; Received 53 B
;; Time 2021-01-01 15:40:30 CET
;; From 116.202.176.26@853(TCP) in 92.9 ms
```

``` 
$ dig @116.202.176.26 heise.de

; <<>> DiG 9.16.10 <<>> @116.202.176.26 heise.de
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```

**Comment by qdm12** [comment]
Strange, I'm investigating. Maybe the root key / named root are expired on my repo, I'll check.

**Comment by qdm12** [comment]
It's because libredns doesn't support DNSSEC. I disabled it in Unbound if one of the providers is LibreDNS, and now it works 👍

**Comment by axel-dd** [comment]
Thanks now everything works fine.
